"""fixed duedate

Revision ID: 016c89890b85
Revises: 357a1a120d01
Create Date: 2024-10-31 15:03:44.073912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '016c89890b85'
down_revision: Union[str, None] = '357a1a120d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'dueDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('dueDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
